# fly.toml app configuration file generated for francis-phonebook on 2023-10-08T13:43:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "francis-phonebook"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
